### ISSUE TITLE
BeatlesBlog.SimConnect' could not be Found

### ISSUE THREAD

**Issue by earmand** [ollyau/EFBConnect#3]
I am trying to build the package and am getting a "The referenced component 'BeatlesBlog.SimConnect' could not be found.   Is there something I need to do to include the package from the External Folder?     I am launching Visual Studio by clicking on the EFBConnct.sln file.    

Thanks for your support!!!  This program seems like it is exactly what I am looking for

**Comment by ollyau** [comment]
You'll have to add the External folder to your NuGet package sources (in Tools -> Options -> NuGet Package Manager -> Package Sources), then possibly(?) install the package (`Install-Package BeatlesBlog.SimConnect` in the package manager console) before you can build the project.

Keep in mind that currently Microsoft Flight Simulator has performance issues with its implementation of the SimConnect server, so your performance may be impacted if you use EFB Connect with Microsoft Flight Simulator 1.7.12.0.  A fix is expected in the next week or so according to the [official blog](https://www.flightsimulator.com/august-27th-2020-development-update/).

**Comment by earmand** [comment]
Thank you!!!

Sorry for the newbie question; I am new to the Visual Studio environment.

Great App!!!!

Dan
