### ISSUE TITLE
"." vs ","?

### ISSUE THREAD

**Issue by halset** [ollyau/EFBConnect#5]
I am trying to get EFBConnect to work on a pc configured with Norwegian language. Here is an example message fra EFBConnect:

```
XGPSMSFS,-111,82274,34,84421,1304,4,312,647,0
```

It looks like EFBConnect is using "," as a decimal separator. Perhaps as the Norwegian language uses "," as a decimal separator. However as this is a fixed protocol, it should probably use a hard coded "." as the decimal separator instead.

**Comment by halset** [comment]
Changing decimal separator from "," to "." on the pc fixed the problem. However, it would be very nice if this could be hardcoded to use "." regardless of the language settings.

**Comment by ollyau** [comment]
Ah, thanks for raising this!  I've made a new version (https://github.com/ollyau/EFBConnect/releases/tag/v1.1.1) which I think should fix this.  Please let me know if it works!

**Comment by ollyau** [comment]
Since it's been a couple weeks and I haven't heard back, I'll assume that everything's working as intended now.  Feel free to re-open the issue if it's still not resolved!

**Comment by halset** [comment]
Thanks and sorry. I have not been able to test this, but thank you for the fix! I will comment when/if I will be able to test this.

**Comment by rick69er** [comment]
when i open my tablet it only has 2 websites how do i add youtube

**Comment by ollyau** [comment]
@rick69er This GitHub repository pertains to EFB Connect, an application that sends position, attitude, and traffic information from Microsoft Flight Simulator to ForeFlight (an EFB running on a physical iPad).  I'm not sure what tablet you're using, but you're more likely to get help from the manufacturer/developer/sellers of the software you're using.
